services:
  redis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-broker
    ports:
      - 6379:6379
    container_name: ubi-manifest-redis

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-workers
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-beat
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt
    depends_on:
      - redis
      - worker

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt
    command:
      - /bin/sh
      - -c
      - >-
        uvicorn ubi_manifest.app.factory:create_app --factory --reload --host 0.0.0.0 --port 8000 --log-config /src/conf/logging.ini
    ports:
      - 8000:8000
    depends_on:
      - redis
      - worker

# TODO make the 'app' and 'workers' automatically reload on code change
